name: Daily Reddit Scraper

on:
  schedule:
    # - cron: '0 0 * * *'
    # - cron: '15 21 * * *'
    - cron: '0 13,19,2 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Clean Whisper Model Cache
        run: |
          rm -rf ~/.cache/whisper

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the main script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
          TEMP_CLIENT_SECRETS_FILE: ${{ secrets.TEMP_CLIENT_SECRETS_FILE }}
          YOUTUBE_CLIENT_SECRETS_FILE: ${{ secrets.YOUTUBE_CLIENT_SECRETS_FILE }}
        run: |
          python main.py --subreddit_name "random"
